<?php
/**
 * Created by PhpStorm.
 * User: nbgsys
 * Date: 2/11/15
 * Time: 11:08 PM
 */

$form = $this->form;
$form->prepare();
$form->setAttribute('action', $this->url(NULL,
    array('controller'=>'Register', 'action' => 'process')));
$form->setAttribute('method', 'post');
?>
<section class="register">
    <h2>Register</h2>
    <?php if ($this->error): ?>
    <p class="error">
        There were one or more issues with your submission.
        Please correct them as indicated below.
    </p>
    <?php endif ?>

    <?php echo $this->form()->openTag($form); ?>

    <dl class="zend_form">
        <dt><?php echo $this->formLabel($form->get('name')); ?></dt>
        <dd>
            <?php
                echo $this->formElement($form->get('name'));
                echo $this->formElementErrors($form->get('name'));
            ?>
        </dd>
        <dt><?php echo $this->formLabel($form->get('email')); ?></dt>
        <dd>
            <?php
                echo $this->formElement($form->get('email'));
                echo $this->formElementErrors($form->get('email'));
            ?>
        </dd>
        <dt><?php echo $this->formLabel($form->get('password')); ?></dt>
        <dd>
            <?php
                echo $this->formElement($form->get('password'));
                echo $this->formElementErrors($form->get('password'));
            ?>
        </dd>
        <dt><?php echo $this->formLabel($form->get('password_confirmation')); ?></dt>
        <dd>
            <?php
            echo $this->formElement($form->get('password_confirmation'));
            echo $this->formElementErrors($form->get('password_confirmation'));
            ?>
        </dd>
        <dd>
            <?php
                echo $this->formElement($form->get('submit'));
                echo $this->formElementErrors($form->get('submit'));
            ?>
        </dd>
    </dl>
    <?php echo $this->form()->closeTag($form); ?>
</section>